# Generated by Django 5.0.4 on 2024-06-18 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Ingrese el nombre de usuario...', max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(help_text='Ingrese el correo electrónico...', max_length=50, unique=True, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(blank=True, help_text='Ingrese su nombre...', max_length=50, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, help_text='Ingrese su apellido...', max_length=50, null=True, verbose_name='Apellido')),
                ('user_active', models.BooleanField(default=True)),
                ('user_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='Ingrese su número de identificación', max_length=10, unique=True, verbose_name='Número de identificación')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Imagen de Perfil')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('address', models.CharField(blank=True, help_text='Ingrese su dirección', max_length=250, null=True, verbose_name='Dirección')),
                ('telephone', models.CharField(blank=True, help_text='Ingrese su número de teléfono', max_length=20, null=True, verbose_name='Número de teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
