# Generated by Django 5.0.4 on 2024-06-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user_admin',
            new_name='is_admin',
        ),
    ]
