# Generated by Django 5.0.4 on 2024-06-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_profileuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='dni',
            field=models.CharField(blank=True, help_text='Ingrese su número de identificación', max_length=10, null=True, unique=True, verbose_name='Número de identificación'),
        ),
    ]
