# Generated by Django 5.0.4 on 2024-08-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/', verbose_name='Imagen de Perfil'),
        ),
    ]
