# Generated by Django 5.0.4 on 2024-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_profileuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', max_length=255, null=True, upload_to='avatars/', verbose_name='Imagen de Perfil'),
        ),
    ]
